language: node_js
sudo: false
node_js:
  - "8.9.2"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - gulp build
notifications:
  email:
    recipients:
      - thomas@tarcgn.de
branches:
  only:
    - master
deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  on:
    branch: master